language: julia
julia:
  - 0.4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-biopython
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq mafft
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.add("PyCall"); ENV["PYTHON"]=""; Pkg.build("PyCall");'
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("BiomolecularStructures"); Pkg.test("BiomolecularStructures"; coverage=true)'  
after_success:
  - julia -e 'cd(Pkg.dir("BiomolecularStructures")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'